WITH

EMPLOYEES AS (

    SELECT * FROM {{ source('tech_store', 'employee') }}

),

FINAL AS (

    SELECT
        ID AS EMPLOYEE_ID,
        FNAME AS FIRST_NAME,
        LNAME AS LAST_NAME,
        CONCAT(FIRST_NAME, ' ', LAST_NAME) AS FULL_NAME,
        HIREDATE AS HIRED_AT,
        ENDDATE AS TERMINATED_AT,
        IFF(TERMINATED_AT IS NULL, TRUE, FALSE) AS IS_ACTIVE
    FROM EMPLOYEES

)

SELECT * FROM FINAL
