name: 'dbt_exercise'
version: '1.0.0'
config-version: 2

profile: 'dbt_exercise'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_exercise:
    staging:  # directory path, applies configs to all models in the parent folder
      +materialized: view
