dbt_exercise:
  target: dev
  outputs:
    dev:
      account: gnecycg-sk19631 # replace with your account identifier
      user: dbt_user
      database: DBT_DEV
      password: Arch2024Enablement!
      role: dbt_dev_role
      schema: public
      threads: 2
      type: snowflake
      warehouse: dbt_dev_wh
    prod:
      account: gnecycg-sk19631 # replace with your account identifier
      user: dbt_user
      database: DBT_PROD
      password: Arch2024Enablement!
      role: dbt_prod_role
      schema: public
      threads: 2
      type: snowflake
      warehouse: dbt_dev_wh

